### ISSUE TITLE
multi-user mode

### ISSUE THREAD

**Issue by pyldin601** [pyldin601/musicloud#38]
**Todo:**
- [ ] Application can be used by more than one user
- [ ] Each user has access to its own library
- [ ] Application can have up to N users
- [ ] Each user can lock access to its library with a password
