### ISSUE TITLE
provider-independent storage

### ISSUE THREAD

**Issue by pyldin601** [pyldin601/musicloud#39]
**Todo:**
- [ ] Allow using custom data storage provider instead of local volumes
- [ ] Backup media library database to data storage (periodically or on-demand)
- [ ] Restore media library database from data storage
